# Generated by Django 5.2.14 on 2026-05-06 13:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('passport', models.CharField(blank=True, max_length=64, verbose_name='Паспорт')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('unit', models.CharField(choices=[('шт', 'шт'), ('м', 'м'), ('кг', 'кг'), ('компл', 'компл')], default='шт', max_length=10, verbose_name='Ед. изм.')),
                ('stock_total', models.PositiveIntegerField(default=0, verbose_name='Всего на складе')),
                ('daily_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена за сутки')),
                ('deposit_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Залог за единицу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
                ('due_date', models.DateField(verbose_name='Срок возврата')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('closed', 'Закрыта'), ('overdue', 'Просрочена')], default='active', max_length=10, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals_created', to=settings.AUTH_USER_MODEL, verbose_name='Оформил')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='core.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('kind', models.CharField(choices=[('deposit', 'Залог'), ('rent', 'Аренда'), ('fine', 'Штраф'), ('refund', 'Возврат залога')], max_length=10, verbose_name='Тип')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.rental', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Количество')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за сутки (снимок)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_items', to='core.product', verbose_name='Товар')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.rental', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Позиция аренды',
                'verbose_name_plural': 'Позиции аренды',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('issue', 'Выдача'), ('return', 'Возврат')], max_length=10, verbose_name='Тип')),
                ('qty', models.PositiveIntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Оформил')),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.rentalitem', verbose_name='Позиция аренды')),
            ],
            options={
                'verbose_name': 'Движение',
                'verbose_name_plural': 'Движения',
                'ordering': ['-date'],
            },
        ),
    ]
