# Generated by Django 5.2.14 on 2026-05-06 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыта'),
        ),
        migrations.AddField(
            model_name='rental',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rentals_closed', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл'),
        ),
    ]
