# Generated by Django 5.2.14 on 2026-05-13 00:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID чата для напоминаний (клиент должен сначала написать боту /start). Узнать ID можно через @userinfobot.', null=True, unique=True, verbose_name='Telegram chat ID'),
        ),
        migrations.CreateModel(
            name='DebtorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('day_before', 'За день до возврата'), ('hour_overdue', 'Часовое напоминание о просрочке')], max_length=20, verbose_name='Тип')),
                ('target_kind', models.CharField(choices=[('customer', 'Клиенту'), ('admin', 'Админу')], max_length=10, verbose_name='Получатель')),
                ('target_chat_id', models.BigIntegerField(verbose_name='Telegram chat ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Отправлено')),
                ('ok', models.BooleanField(default=True, verbose_name='Успех')),
                ('response', models.TextField(blank=True, verbose_name='Ответ API')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_notifications', to='core.rental', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Уведомление должнику',
                'verbose_name_plural': 'Уведомления должникам',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['rental', 'kind', 'sent_at'], name='core_debtor_rental__8cce89_idx')],
            },
        ),
    ]
