# Generated by Django 5.2.14 on 2026-05-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_telegram_chat_id_debtornotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtornotification',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Уведомление о долге', 'verbose_name_plural': 'Уведомления о долгах'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='debtornotification',
            name='target_kind',
        ),
    ]
