# Generated by Django 5.2.14 on 2026-05-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rental_due_date_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], default='cash', max_length=10, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Залог'), ('advance', 'Аванс'), ('rent', 'Аренда'), ('fine', 'Штраф'), ('refund', 'Возврат залога')], max_length=10, verbose_name='Тип'),
        ),
    ]
