# Generated by Django 5.2.14 on 2026-05-22 21:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment_method_alter_payment_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Рабочий',
                'verbose_name_plural': 'Рабочие',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('is_present', models.BooleanField(default=True, verbose_name='Присутствовал')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда отметили')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_marks', to=settings.AUTH_USER_MODEL, verbose_name='Кто отметил')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.worker', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'ordering': ['-date', 'worker__full_name'],
                'indexes': [models.Index(fields=['date', 'is_present'], name='core_attend_date_7db2e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('worker', 'date'), name='uniq_worker_date_attendance')],
            },
        ),
    ]
