# Generated by Django 5.2.14 on 2026-05-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_worker_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expected_max_days',
            field=models.PositiveIntegerField(blank=True, help_text='После этого срока позиция подсвечивается красным.', null=True, verbose_name='Норма, дней (макс)'),
        ),
        migrations.AddField(
            model_name='product',
            name='expected_min_days',
            field=models.PositiveIntegerField(blank=True, help_text='Если задано, помогает оператору заметить превышение.', null=True, verbose_name='Норма, дней (мин)'),
        ),
    ]
