# Generated by Django 5.2.14 on 2026-06-01 14:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seed_norm_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Стандартная зарплата за полный месяц (без премий).', max_digits=12, verbose_name='Оклад за месяц'),
        ),
        migrations.CreateModel(
            name='SalaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(db_index=True, verbose_name='Месяц')),
                ('kind', models.CharField(choices=[('bonus', 'Премия'), ('penalty', 'Штраф/вычет')], default='bonus', max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Когда')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_entries', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_entries', to='core.worker', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'Начисление/удержание',
                'verbose_name_plural': 'Начисления/удержания',
                'ordering': ['-year', '-month', '-created_at'],
                'indexes': [models.Index(fields=['worker', 'year', 'month'], name='core_salary_worker__4e9336_idx')],
            },
        ),
    ]
