# Generated by Django 5.2.14 on 2026-06-02 21:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_worker_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySalaryBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(db_index=True, verbose_name='Месяц')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Оклад за месяц')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_bases', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bases', to='core.worker', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'Оклад за месяц',
                'verbose_name_plural': 'Оклады за месяц',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['worker', 'year', 'month'], name='core_monthl_worker__26e4a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('worker', 'year', 'month'), name='uniq_worker_month_salary_base')],
            },
        ),
    ]
