# Generated by Django 5.2.14 on 2026-06-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_monthlysalarybase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='included_kit',
            field=models.TextField(blank=True, default='', help_text='Что входит в комплект на 1 шт (справочно). Напр.: Зажим ×3, Фиксатор ×3, Штир/шайба ×3', verbose_name='В комплекте'),
        ),
    ]
