# Generated by Django 5.2.14 on 2026-06-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_formwork_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Аренда, начисленная за возвращённые единицы. Только для возвратов; для выдачи и списаний — пусто (тогда считается автоматически по дням × цена).', max_digits=12, null=True, verbose_name='Сумма начисления'),
        ),
    ]
