# Generated by Django 5.2.14 on 2026-07-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_set_stock_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Если задано — клиент в архиве: скрыт из списка и поиска, но данные и история аренд сохранены.', null=True, verbose_name='Архивирован'),
        ),
    ]
